project_id = "avbdwoetjqhgvmflqena"

[functions.elevenlabs-tts]
verify_jwt = false

[functions.freesound-search]
verify_jwt = false

[functions.generate-dialogue]
verify_jwt = false

[functions.generate-shot-image]
verify_jwt = false

[functions.generate-script]
verify_jwt = false

[functions.generate-video]
verify_jwt = false

[functions.rag-ingest]
verify_jwt = false

[functions.rag-search]
verify_jwt = false

[functions.recommend-audio]
verify_jwt = false