-- Re-categorize existing official templates by the app's 8 mood types (情绪风格),
-- then add new official short + long templates so every mood has both.
-- All shots use the same editable schema as user-generated scripts, so loading a
-- template drops straight into the storyboard editor.

-- ── 1. Align existing templates' category with the app's mood taxonomy ──
UPDATE public.script_templates SET category = '治愈'
  WHERE is_official = true AND title IN ('雨后森林漫步', '一碗面的故事', '流浪猫日记', '那年夏天');
UPDATE public.script_templates SET category = '文艺'
  WHERE is_official = true AND title IN ('霓虹都市独白', '毕业那天', '一期一会');
UPDATE public.script_templates SET category = '史诗'
  WHERE is_official = true AND title IN ('太空行走');

-- ── 2. New SHORT templates for the moods that lacked one ──
INSERT INTO public.script_templates (title, category, emoji, description, mood, duration_type, shots, is_official, created_by) VALUES
(
  '上班迟到进行曲', '搞笑', '😄', '一个倒霉打工人迟到的早晨，意外接连上演，节奏明快的喜剧短片。', 'funny', 'short',
  '[{"shotNumber":"01","shotType":"特写","visual":"闹钟显示8:58，一只手猛拍下去，下一秒瞳孔地震","duration":"3s","dialogue":"（内心）完了完了完了！","audio":"闹钟铃声戛然而止、急促心跳","character":"阿强 — 二十五岁，永远在迟到","directorNote":"用快速变焦放大瞳孔，制造夸张喜感","emotionIntensity":60},{"shotNumber":"02","shotType":"中景","visual":"阿强单脚跳着穿裤子撞到门框，牙刷还叼在嘴里","duration":"4s","dialogue":"","audio":"砰的撞击声、含混的哀嚎","character":"","directorNote":"手持跟拍制造慌乱感，动作要夸张","emotionIntensity":65},{"shotNumber":"03","shotType":"近景","visual":"电梯门即将关闭，阿强飞扑伸手，手却被门反复夹弹回来","duration":"5s","dialogue":"（喊）等一下——！","audio":"电梯提示音、邻居憋笑声","character":"邻居大妈 — 看热闹不嫌事大","directorNote":"慢动作飞扑接正常速度被夹，节奏反差出笑点","emotionIntensity":70},{"shotNumber":"04","shotType":"中景","visual":"公交车正好开走，阿强追着跑两步，绝望地扶膝盖喘气","duration":"5s","dialogue":"","audio":"公交引擎声远去、粗重喘息","character":"","directorNote":"长焦压缩，强调车与人拉开的距离","emotionIntensity":55},{"shotNumber":"05","shotType":"特写","visual":"共享单车扫码三次失败，屏幕显示该车已被预定，阿强表情凝固","duration":"4s","dialogue":"（内心）老天爷你不要玩我。","audio":"扫码失败提示音三连","character":"","directorNote":"定格在凝固表情，加一拍静默","emotionIntensity":75},{"shotNumber":"06","shotType":"远景","visual":"阿强冲进公司大厅，打卡机显示9:01，他瘫倒在地，背景同事鼓掌","duration":"6s","dialogue":"（旁白）人生啊，输在了最后一分钟。","audio":"打卡失败音、同事哄笑掌声","character":"","directorNote":"高机位俯拍瘫倒，喜剧式收尾","emotionIntensity":50}]'::jsonb,
  true, NULL
),
(
  '凌晨三点的来电', '悬疑', '🔍', '一通来自已注销号码的深夜来电，揭开一段被刻意遗忘的往事，烧脑悬疑短片。', 'suspense', 'short',
  '[{"shotNumber":"01","shotType":"特写","visual":"手机屏幕在黑暗中亮起，陌生号码来电，时间03:00","duration":"5s","dialogue":"","audio":"手机震动声、寂静的房间","character":"林夏 — 三十岁，独居女性","directorNote":"极暗环境仅屏幕光，营造压迫感","emotionIntensity":45},{"shotNumber":"02","shotType":"中景","visual":"林夏迟疑地接起，听筒里只有沙沙电流声和模糊的呼吸","duration":"6s","dialogue":"（试探）喂？……你是谁？","audio":"电流杂音、若有若无的呼吸","character":"","directorNote":"侧光打出半张脸，保留悬念","emotionIntensity":60},{"shotNumber":"03","shotType":"近景","visual":"她发现来电号码竟和三年前车祸中逝去好友的号码一模一样","duration":"5s","dialogue":"（颤抖）这不可能……这个号码早就注销了。","audio":"心跳放大、电流声渐强","character":"","directorNote":"手机屏幕与旧照片交叉剪辑","emotionIntensity":80},{"shotNumber":"04","shotType":"特写","visual":"听筒突然传出清晰一句，是只有她和好友才知道的暗号","duration":"4s","dialogue":"（听筒）你还记得那天，我让你别上那辆车。","audio":"失真的人声、骤然的静默","character":"神秘来电者","directorNote":"声音加混响失真，制造不寒而栗","emotionIntensity":90},{"shotNumber":"05","shotType":"中景","visual":"林夏猛拉开抽屉翻出当年的报纸，标题里藏着被她忽略的细节","duration":"6s","dialogue":"","audio":"纸张翻动声、急促呼吸","character":"","directorNote":"浅景深逐字对焦报纸标题","emotionIntensity":70},{"shotNumber":"06","shotType":"远景","visual":"窗外天色微亮，电话已挂断，桌上多了一张她从未见过的旧车票","duration":"6s","dialogue":"（旁白）有些电话，是过去打来索取答案的。","audio":"晨鸟声、座钟滴答","character":"","directorNote":"固定机位拉开，留白收尾引发回味","emotionIntensity":55}]'::jsonb,
  true, NULL
),
(
  '绝杀0.4秒', '热血', '🔥', '篮球决赛最后0.4秒，落后两分的替补少年迎来人生第一次出手，逆风翻盘的热血时刻。', 'passionate', 'short',
  '[{"shotNumber":"01","shotType":"远景","visual":"体育馆记分牌78比80，比赛剩0.4秒，全场观众起立屏息","duration":"5s","dialogue":"（解说）只剩0.4秒，他们还落后两分！","audio":"全场轰鸣、解说嘶吼","character":"","directorNote":"高机位俯拍全场，建立紧张气压","emotionIntensity":70},{"shotNumber":"02","shotType":"中景","visual":"教练蹲在场边布置最后一攻，所有人看向一直坐冷板凳的少年","duration":"5s","dialogue":"（教练）这球，给你。","audio":"暂停哨音、队友喘息","character":"陈野 — 十七岁，从未在正赛得分的替补","directorNote":"围圈构图，焦点收束到少年脸上","emotionIntensity":65},{"shotNumber":"03","shotType":"特写","visual":"少年攥紧球衣下摆，手心全是汗，深吸一口气抬头，眼神变了","duration":"4s","dialogue":"（内心）这一次，我不躲。","audio":"心跳声放大、环境音抽离","character":"","directorNote":"极浅景深，只有眼睛清晰","emotionIntensity":75},{"shotNumber":"04","shotType":"中景","visual":"发球哨响，少年绕过掩护飞奔到三分线，队友越过半场精准长传","duration":"5s","dialogue":"","audio":"球鞋摩擦地板的尖锐声、呼喊","character":"","directorNote":"稳定器横移跟拍，速度感拉满","emotionIntensity":80},{"shotNumber":"05","shotType":"特写","visual":"少年接球瞬间高高跃起，篮球离手，时间仿佛在指尖凝固","duration":"5s","dialogue":"","audio":"全场静默、唯有篮球划破空气声","character":"","directorNote":"子弹时间慢镜，环绕拍摄出手姿态","emotionIntensity":95},{"shotNumber":"06","shotType":"远景","visual":"球应声入网，蜂鸣器响起，少年被狂奔而来的队友扑倒淹没在人海","duration":"6s","dialogue":"（解说）进了——！他做到了！","audio":"蜂鸣器、爆炸般的欢呼","character":"","directorNote":"慢动作转正常速度，情绪彻底释放","emotionIntensity":100}]'::jsonb,
  true, NULL
),
(
  '十三层', '恐怖', '👻', '加班深夜，独自乘坐的电梯停在了这栋楼本不存在的第十三层，心理恐怖短片。', 'horror', 'short',
  '[{"shotNumber":"01","shotType":"中景","visual":"深夜空荡的写字楼大堂，加班女白领走进电梯，按下18楼","duration":"5s","dialogue":"","audio":"电梯运行嗡鸣、日光灯电流声","character":"苏苏 — 二十八岁，加班到深夜","directorNote":"冷白光，构图刻意空旷","emotionIntensity":30},{"shotNumber":"02","shotType":"特写","visual":"楼层数字跳动，13突然亮起，电梯一震停下，门缓缓打开","duration":"5s","dialogue":"（自语）这栋楼……没有13层啊。","audio":"电梯急停的金属声、门开启声","character":"","directorNote":"数字特写后切门缝，制造未知恐惧","emotionIntensity":55},{"shotNumber":"03","shotType":"中景","visual":"门外是与楼上一模一样、却空无一人的走廊，灯一盏盏亮起","duration":"6s","dialogue":"","audio":"灯管逐个点亮的啪嗒声、死寂","character":"","directorNote":"走廊纵深透视，灯依次亮起引导视线","emotionIntensity":65},{"shotNumber":"04","shotType":"近景","visual":"走廊尽头茶水间，一个背对的身影在缓慢接水，水却一直溢出","duration":"5s","dialogue":"（颤声）请问……有人吗？","audio":"持续的流水声、苏苏的呼吸","character":"背影 — 不可名状","directorNote":"浅景深，背影始终虚化不给正脸","emotionIntensity":80},{"shotNumber":"05","shotType":"特写","visual":"苏苏疯狂按关门键，反光的电梯门上，那身影已站到她身后","duration":"4s","dialogue":"","audio":"按键声急促、一声极轻的耳语","character":"","directorNote":"利用电梯门镜面反射制造窒息感","emotionIntensity":95},{"shotNumber":"06","shotType":"远景","visual":"电梯门合拢重新运行，数字从13跳回1，开门时保安茫然看着空电梯","duration":"6s","dialogue":"（保安）奇怪，这电梯怎么自己上去又下来了。","audio":"电梯到站提示音、空旷回响","character":"保安 — 值夜班","directorNote":"固定机位，空电梯收尾留余韵","emotionIntensity":60}]'::jsonb,
  true, NULL
),
(
  '共享一把伞', '浪漫', '💕', '一场突如其来的暴雨，一把不够大的伞，两个陌生人之间悄然萌发的心动，清新浪漫短片。', 'romantic', 'short',
  '[{"shotNumber":"01","shotType":"远景","visual":"傍晚的地铁口暴雨倾盆，一群人挤在屋檐下等雨停","duration":"5s","dialogue":"","audio":"哗啦的雨声、车流溅水声","character":"","directorNote":"雨幕逆光，营造朦胧氛围","emotionIntensity":30},{"shotNumber":"02","shotType":"中景","visual":"女孩翻遍背包只有一把迷你折叠伞，犹豫着撑开走进雨里","duration":"5s","dialogue":"","audio":"雨打伞面声、脚步踩水","character":"念念 — 二十二岁，刚下班的设计师","directorNote":"跟拍背影，伞太小淋湿半边肩","emotionIntensity":40},{"shotNumber":"03","shotType":"近景","visual":"一个男生快步跟上，默默让出半边身子替她挡住斜飘的雨","duration":"5s","dialogue":"（男生）你的伞，好像不太够用。","audio":"雨声、略显紧张的对话","character":"程亦 — 二十四岁，常坐同一班地铁","directorNote":"两人并肩特写，伞下的距离感是重点","emotionIntensity":60},{"shotNumber":"04","shotType":"特写","visual":"伞下两人的手不经意碰到一起，又像触电般收回，相视一笑","duration":"4s","dialogue":"","audio":"雨声渐柔、轻笑","character":"","directorNote":"浅景深拍交握又松开的手，心动细节","emotionIntensity":75},{"shotNumber":"05","shotType":"中景","visual":"雨渐停，两人却谁都没提收伞，慢慢沿着湿漉漉的街道走","duration":"6s","dialogue":"（念念）其实……雨好像停了。（程亦）嗯，我没注意。","audio":"滴答的余雨、远处晚风","character":"","directorNote":"侧后方跟拍，暖色路灯渐次亮起","emotionIntensity":70},{"shotNumber":"06","shotType":"远景","visual":"街角，女孩把伞塞给男生当作再见的理由，伞柄上贴着写了号码的便签","duration":"6s","dialogue":"（旁白）有些相遇，是借一把伞的名义，留住一个人。","audio":"温柔钢琴渐入、夜街环境声","character":"","directorNote":"固定机位，两人反向走开又同时回头","emotionIntensity":80}]'::jsonb,
  true, NULL
);

-- ── 3. New LONG templates — every mood gets a deep, multi-scene script ──
INSERT INTO public.script_templates (title, category, emoji, description, mood, duration_type, shots, is_official, created_by) VALUES
(
  '向阳面包店', '治愈', '🍞', '都市失意的女孩回到海边小镇，接手外婆留下的面包店，在麦香与人情中重新找回生活的温度。深度治愈长片。', 'healing', 'long',
  '[{"shotNumber":"01","shotType":"大远景","visual":"清晨的海边小镇全景，白墙红瓦，一辆长途巴士停在路口","duration":"7s","dialogue":"","audio":"海浪声、海鸥鸣叫","character":"","directorNote":"【第一幕·归来】航拍缓推建立地域感","emotionIntensity":25},{"shotNumber":"02","shotType":"中景","visual":"拖着行李箱的女孩站在一家落锁的旧面包店前，招牌褪色斑驳","duration":"6s","dialogue":"（旁白）外婆走后，这家店空了整整一年。","audio":"行李箱滚轮声、风铃轻响","character":"小满 — 二十六岁，刚辞掉城里的工作","directorNote":"逆光剪影，强调人与旧店的关系","emotionIntensity":40},{"shotNumber":"03","shotType":"特写","visual":"她推开门，灰尘在光柱中飞舞，墙上还贴着外婆手写的面包配方","duration":"5s","dialogue":"","audio":"门轴吱呀声、寂静","character":"","directorNote":"丁达尔光柱中的尘埃，怀旧氛围","emotionIntensity":55},{"shotNumber":"04","shotType":"中景","visual":"小满系上外婆的旧围裙笨拙揉面，第一炉却烤糊了，她沮丧坐下","duration":"6s","dialogue":"","audio":"烤箱计时器、一声叹息","character":"","directorNote":"【第二幕·重启】暖色厨房，失败的烟火气","emotionIntensity":45},{"shotNumber":"05","shotType":"近景","visual":"隔壁修船的老伯送来一筐海盐，说外婆的面包当年救过他的胃","duration":"6s","dialogue":"（老伯）你外婆说，面包要放一点海的味道。","audio":"木门推开声、爽朗笑声","character":"阿海伯 — 六十岁，镇上的老邻居","directorNote":"侧光人物，传递人情温度","emotionIntensity":60},{"shotNumber":"06","shotType":"中景","visual":"镇上孩子趴在橱窗外看小满烤面包，她笑着递出第一块成功的吐司","duration":"5s","dialogue":"（孩子）姐姐，好香！","audio":"孩子嬉笑、烤箱叮的一声","character":"镇上的孩子们","directorNote":"橱窗内外构图，玻璃上的哈气","emotionIntensity":70},{"shotNumber":"07","shotType":"特写","visual":"深夜，小满对照外婆的配方反复试验，面团终于发酵出理想的样子","duration":"5s","dialogue":"","audio":"座钟滴答、面团轻响","character":"","directorNote":"顶光俯拍双手，专注的仪式感","emotionIntensity":65},{"shotNumber":"08","shotType":"远景","visual":"重新开业那天，褪色招牌被擦亮，门口排起小小的队伍","duration":"6s","dialogue":"","audio":"风铃、人群低语、海浪","character":"","directorNote":"【第三幕·新生】固定机位，晨光中的小店","emotionIntensity":75},{"shotNumber":"09","shotType":"近景","visual":"小满把第一炉面包摆上货架，抬头看见墙上外婆的照片，轻声说话","duration":"5s","dialogue":"（轻声）外婆，我把店开回来了。","audio":"轻柔弦乐渐入","character":"","directorNote":"面部特写，眼里有光也有泪","emotionIntensity":85},{"shotNumber":"10","shotType":"大远景","visual":"黄昏小镇，面包店暖黄的灯亮着，麦香仿佛随海风飘向整条街","duration":"7s","dialogue":"（旁白）原来回家，是从揉好一块面团开始的。","audio":"弦乐渐强后归于海浪","character":"","directorNote":"航拍拉升，与开场呼应收尾","emotionIntensity":60}]'::jsonb,
  true, NULL
),
(
  '最后的旧书店', '文艺', '📖', '城市更新的浪潮中，一家即将拆迁的旧书店迎来最后七天，店主与读者们用各自的方式与时光告别。文艺长片。', 'literary', 'long',
  '[{"shotNumber":"01","shotType":"远景","visual":"老城区窄巷尽头，斑驳的旧书店亮着昏黄的灯，墙上贴着拆迁公告","duration":"7s","dialogue":"","audio":"城市远处车流、风吹纸张","character":"","directorNote":"【第一幕·告别通知】固定机位，纵深巷弄","emotionIntensity":30},{"shotNumber":"02","shotType":"中景","visual":"白发店主用抹布一本本擦拭书脊，动作缓慢而郑重","duration":"6s","dialogue":"（旁白）这家店，比我女儿的年纪还要大。","audio":"抹布摩擦声、老唱片机","character":"老周 — 七十岁，守店四十年","directorNote":"侧逆光，灰尘与时光感","emotionIntensity":45},{"shotNumber":"03","shotType":"特写","visual":"一封夹在旧书里的泛黄情书滑落，落款是几十年前的日期","duration":"5s","dialogue":"","audio":"纸张飘落声","character":"","directorNote":"微距对焦褪色字迹，留白想象","emotionIntensity":55},{"shotNumber":"04","shotType":"中景","visual":"一个女孩每天放学都来，蹲在角落读完同一套没钱买的小说","duration":"6s","dialogue":"（女孩）老板，我还差最后一本就读完了。","audio":"翻书声、巷口叫卖","character":"阿萤 — 十六岁，常来蹭书的学生","directorNote":"【第二幕·最后的读者】暖光，人物融入书架","emotionIntensity":50},{"shotNumber":"05","shotType":"近景","visual":"老周默默把那套书从货架取下，用牛皮纸包好放进女孩书包","duration":"5s","dialogue":"（老周）拿去吧，书要遇到读它的人才算活着。","audio":"牛皮纸窸窣声","character":"","directorNote":"双手特写，传递的仪式感","emotionIntensity":70},{"shotNumber":"06","shotType":"中景","visual":"老顾客们陆续赶来，有人朗读，有人合影，书店里第一次这样热闹","duration":"6s","dialogue":"","audio":"交谈声、笑声、翻书声交织","character":"老顾客们","directorNote":"中景群像，暖色调，人间烟火","emotionIntensity":65},{"shotNumber":"07","shotType":"特写","visual":"墙上的旧挂钟、读者留言本、外婆牌台灯，被镜头一一温柔抚过","duration":"6s","dialogue":"","audio":"钟摆声、笔尖书写声","character":"","directorNote":"一组空镜慢摇，凝视细节","emotionIntensity":60},{"shotNumber":"08","shotType":"中景","visual":"最后一夜，老周独自坐在书堆中，借着台灯读完那封泛黄的情书","duration":"6s","dialogue":"（旁白）原来每本书里，都藏着一个没说完的故事。","audio":"翻页声、窗外夜雨","character":"老周","directorNote":"【第三幕·熄灯】单人灯下构图，文学性凝视","emotionIntensity":80},{"shotNumber":"09","shotType":"近景","visual":"清晨，老周郑重地拉下卷帘门，把钥匙轻轻放进信箱","duration":"5s","dialogue":"","audio":"卷帘门金属声、钥匙落地","character":"","directorNote":"手部特写，告别的克制","emotionIntensity":75},{"shotNumber":"10","shotType":"大远景","visual":"巷口，女孩抱着那套书回头望了一眼，旧书店的灯永远地暗了下去","duration":"7s","dialogue":"（旁白）有些地方会消失，但它给过的光，会一直亮在某个人心里。","audio":"钢琴独奏渐弱、城市苏醒","character":"阿萤","directorNote":"固定长镜，让人物走出画面收尾","emotionIntensity":70}]'::jsonb,
  true, NULL
),
(
  '烽燧', '史诗', '⚔️', '大漠孤烟，一座边关烽火台上，最后三名戍卒在援军未至的绝境中，用生命点燃了那一束警示的狼烟。史诗长片。', 'epic', 'long',
  '[{"shotNumber":"01","shotType":"大远景","visual":"黄昏的戈壁大漠，一座孤零零的烽燧矗立在天地之间","duration":"7s","dialogue":"","audio":"呼啸的风沙、苍凉号角","character":"","directorNote":"【第一幕·孤燧】航拍极远景，人与天地的渺小","emotionIntensity":35},{"shotNumber":"02","shotType":"中景","visual":"烽火台上，老兵眺望远方扬起的沙尘，神色骤然凝重","duration":"6s","dialogue":"（老兵）来了，比探报说的还要快。","audio":"风声、铠甲碰撞","character":"校尉老秦 — 五十岁，戍边三十年","directorNote":"侧逆光剪影，凝视的力量","emotionIntensity":50},{"shotNumber":"03","shotType":"近景","visual":"年轻戍卒的手紧握长戈，指节发白，眼里有恐惧也有倔强","duration":"5s","dialogue":"（年轻戍卒）校尉，援军……还有多久？","audio":"心跳、远处隐约马蹄","character":"戍卒阿木 — 十九岁，第一次上战场","directorNote":"极浅景深，恐惧与勇气并存","emotionIntensity":55},{"shotNumber":"04","shotType":"远景","visual":"地平线上，黑压压的骑兵如潮水般漫过沙丘，遮天蔽日","duration":"6s","dialogue":"","audio":"雷鸣般的马蹄、号角骤起","character":"","directorNote":"【第二幕·绝境】大广角展现压倒性兵力","emotionIntensity":70},{"shotNumber":"05","shotType":"中景","visual":"老秦将最后一捆狼烟柴草搬上燧顶，三人合力点燃火种","duration":"6s","dialogue":"（老秦）只要这把火点起来，三百里外就知道敌人来了。","audio":"柴草噼啪、风助火势","character":"三名戍卒","directorNote":"火光映脸，仰拍英雄群像","emotionIntensity":75},{"shotNumber":"06","shotType":"特写","visual":"火把凑近柴草的瞬间，狼烟腾空而起，笔直冲入苍穹","duration":"5s","dialogue":"","audio":"烈焰轰燃、号角长鸣","character":"","directorNote":"仰拍狼烟直上，全片视觉支点","emotionIntensity":85},{"shotNumber":"07","shotType":"中景","visual":"敌骑攻上燧台，三人背靠背挥戈死战，以一当十","duration":"6s","dialogue":"（阿木嘶吼）烽火不能灭！","audio":"兵刃相击、嘶吼、风声","character":"三名戍卒","directorNote":"手持跟拍混战，尘土与火光","emotionIntensity":90},{"shotNumber":"08","shotType":"近景","visual":"老秦身中数箭仍死守烽火，回头看了一眼那束不灭的狼烟，欣慰一笑","duration":"5s","dialogue":"（老秦）值了。","audio":"战声渐远、风声呜咽","character":"校尉老秦","directorNote":"【第三幕·不灭】慢镜特写，悲壮的微笑","emotionIntensity":95},{"shotNumber":"09","shotType":"大远景","visual":"夕阳下，烽燧之上狼烟未断，远方天际终于扬起己方援军的旌旗","duration":"7s","dialogue":"（旁白）他们没能等到援军，但援军，因这束烟而来。","audio":"苍凉而恢宏的交响、马蹄渐近","character":"","directorNote":"极远景对比，烟与旗的呼应","emotionIntensity":90},{"shotNumber":"10","shotType":"特写","visual":"战后焦土上，半截染血的长戈插在沙中，狼烟的余烬随风飘散","duration":"6s","dialogue":"（旁白）大漠记得每一个，没有留下名字的人。","audio":"风沙、余烬声、号角余韵","character":"","directorNote":"固定机位空镜，让历史归于沉默","emotionIntensity":70}]'::jsonb,
  true, NULL
),
(
  '五个室友的战争', '搞笑', '😄', '五个性格迥异的年轻人挤在一间老破租房里，从抢厕所到分摊水电，一地鸡毛却笑料百出的都市合租情景喜剧。', 'funny', 'long',
  '[{"shotNumber":"01","shotType":"远景","visual":"老旧居民楼内一间贴满便利贴的合租房，五扇门同时打开又关上","duration":"5s","dialogue":"","audio":"五扇门此起彼伏的开关声、闹钟交响","character":"","directorNote":"【第一幕·早高峰】固定机位看五门齐动，节奏喜感","emotionIntensity":45},{"shotNumber":"02","shotType":"中景","visual":"五人在唯一的卫生间门口排成长队，各自憋着姿势焦躁跳脚","duration":"5s","dialogue":"（程序员）求求了快一点，我九点的会！","audio":"敲门声、催促声、马桶冲水","character":"五位室友 — 程序员、网红、考研党、外卖员、鼓手","directorNote":"一字排开横移，夸张肢体","emotionIntensity":55},{"shotNumber":"03","shotType":"近景","visual":"冰箱贴满标签，网红女孩发现酸奶又被偷喝，怒贴第七张警告条","duration":"4s","dialogue":"（网红）这是本月第七盒！我要装监控了！","audio":"冰箱门吸合声、便利贴撕拉","character":"网红小美","directorNote":"特写满是标签的冰箱，细节笑点","emotionIntensity":50},{"shotNumber":"04","shotType":"中景","visual":"考研党戴降噪耳机刷题，隔壁鼓手疯狂排练架子鼓，墙在抖","duration":"5s","dialogue":"（考研党崩溃）拜托！我还有三十天考试！","audio":"激烈鼓点、墙体震动、哀嚎","character":"考研党阿文、鼓手大鹏","directorNote":"【第二幕·宣战】分屏对比两人，反差喜剧","emotionIntensity":60},{"shotNumber":"05","shotType":"中景","visual":"五人围着一张水电费账单激烈辩论，谁也不肯多掏一块钱","duration":"6s","dialogue":"（外卖员）我天天在外面跑，凭什么平摊电费！","audio":"七嘴八舌的争吵、拍桌","character":"五位室友","directorNote":"环绕拍摄圆桌会议，群口相声式调度","emotionIntensity":55},{"shotNumber":"06","shotType":"近景","visual":"争吵中突然全屋停电，五人黑暗里大眼瞪小眼，齐刷刷掏手机照明","duration":"4s","dialogue":"（齐声）……谁没交电费？","audio":"跳闸声、寂静、五声叹气","character":"五位室友","directorNote":"黑场仅手机光，定格尴尬","emotionIntensity":65},{"shotNumber":"07","shotType":"中景","visual":"没钱叫外卖的深夜，五人翻出各自仅剩的食材，凑了一锅黑暗料理火锅","duration":"6s","dialogue":"（鼓手）我贡献半根火腿肠！（网红）我有一包面膜……啊不是。","audio":"锅咕嘟声、哄笑","character":"五位室友","directorNote":"【第三幕·和解】暖光围炉，氛围转暖","emotionIntensity":70},{"shotNumber":"08","shotType":"近景","visual":"考研党发现，鼓手每天排练其实是想用鼓声当他复习的背景白噪音","duration":"5s","dialogue":"（鼓手挠头）你说你睡不着，我寻思鼓声催眠嘛。","audio":"轻笑、火锅咕嘟声","character":"阿文、大鹏","directorNote":"双人近景，误会化解的温情","emotionIntensity":65},{"shotNumber":"09","shotType":"中景","visual":"五人挤在小阳台吃火锅看夜景，因为停电反而聊了第一次心里话","duration":"6s","dialogue":"（小美）其实……跟你们挤这破房子，还挺好的。","audio":"城市夜风、笑声渐柔","character":"五位室友","directorNote":"阳台群像，暖黄路灯做背景","emotionIntensity":75},{"shotNumber":"10","shotType":"远景","visual":"第二天清晨，卫生间门口又排起长队，这次他们边骂边笑地递牙刷","duration":"6s","dialogue":"（旁白）所谓家人，就是一边嫌弃，一边谁也离不开谁。","audio":"熟悉的早高峰交响、笑闹","character":"五位室友","directorNote":"与开场呼应，循环式喜剧收尾","emotionIntensity":60}]'::jsonb,
  true, NULL
),
(
  '孤岛来客', '悬疑', '🔍', '一场暴风雨把六位陌生人困在与世隔绝的海岛别墅，当第一个人离奇消失，所有人才发现这场聚会从一开始就是精心设计的局。本格推理长片。', 'suspense', 'long',
  '[{"shotNumber":"01","shotType":"远景","visual":"暴风雨之夜，一座孤岛上的现代别墅在闪电中忽明忽暗","duration":"6s","dialogue":"","audio":"惊雷、暴雨、海浪拍岸","character":"","directorNote":"【第一幕·邀约】闪电频闪营造不安","emotionIntensity":40},{"shotNumber":"02","shotType":"中景","visual":"六位互不相识的客人聚在客厅，桌上摆着同样的烫金邀请函","duration":"6s","dialogue":"（律师）所以……我们都不认识这位主人？","audio":"壁炉火声、试探的交谈","character":"六位客人 — 律师、医生、记者、商人、画家、管家","directorNote":"环形构图暗示困局，逐一给脸","emotionIntensity":45},{"shotNumber":"03","shotType":"特写","visual":"每张邀请函背面都印着同一行小字：今夜，有人将为旧事付出代价","duration":"5s","dialogue":"","audio":"雨声、纸张翻动","character":"","directorNote":"微距推近那行字，植入悬念","emotionIntensity":60},{"shotNumber":"04","shotType":"中景","visual":"灯光骤灭又亮起，商人已不见踪影，他的酒杯还在桌上轻轻摇晃","duration":"5s","dialogue":"（记者）人呢？刚才还在这里的！","audio":"跳电声、惊呼、玻璃震颤","character":"五位客人","directorNote":"【第二幕·消失】利用熄灯完成视觉魔术","emotionIntensity":70},{"shotNumber":"05","shotType":"近景","visual":"众人搜查，记者在书房发现一本相册，六人竟在同一桩旧案里都有牵连","duration":"6s","dialogue":"（记者）十年前那场事故……我们每个人都撒了谎。","audio":"翻相册声、雷声","character":"","directorNote":"浅景深扫过一张张旧照，信息揭示","emotionIntensity":65},{"shotNumber":"06","shotType":"中景","visual":"怀疑像瘟疫般蔓延，五人彼此戒备，谁都可能是凶手也可能是下一个","duration":"6s","dialogue":"（医生）在场的每个人，都有杀人的理由。","audio":"紧绷的弦乐、雨声","character":"","directorNote":"五人对峙的不安调度，眼神交错","emotionIntensity":60},{"shotNumber":"07","shotType":"特写","visual":"画家无意发现别墅监控早已运转，录像里有个本不该存在的第七人","duration":"5s","dialogue":"","audio":"监控电流声、心跳","character":"画家","directorNote":"监控雪花画面中的模糊身影","emotionIntensity":75},{"shotNumber":"08","shotType":"中景","visual":"管家平静地端上最后一道餐点，说出了那句改变一切的话","duration":"6s","dialogue":"（管家）各位的位置，从坐下那一刻起，就已经排好了。","audio":"餐具轻响、骤然的静默","character":"管家","directorNote":"【第三幕·真相】平静中的惊雷，反转支点","emotionIntensity":85},{"shotNumber":"09","shotType":"近景","visual":"真相揭开：这是十年前受害者女儿设下的局，为亡父讨一个迟来的承认","duration":"6s","dialogue":"（管家摘下伪装）我等这一夜，等了整整十年。","audio":"低沉钢琴、雨势渐歇","character":"真凶","directorNote":"卸下伪装的特写，动机的重量","emotionIntensity":80},{"shotNumber":"10","shotType":"远景","visual":"天亮雨停，救援船靠岸，别墅门口只留下七副餐具与一封自白书","duration":"7s","dialogue":"（旁白）有些真相，需要一座孤岛，才敢说出口。","audio":"海鸥、引擎声、风","character":"","directorNote":"固定空镜收尾，余味悠长","emotionIntensity":65}]'::jsonb,
  true, NULL
),
(
  '替补席', '热血', '🔥', '一支濒临解散的县城中学足球队，五个被嘲笑的差生少年，在退役教练带领下一路逆袭，向全省冠军发起最后的冲锋。励志热血长片。', 'passionate', 'long',
  '[{"shotNumber":"01","shotType":"远景","visual":"杂草丛生的县城中学操场，破旧球门歪斜，几个少年有气无力地踢球","duration":"6s","dialogue":"（旁白）我们这支队，全校没人看好，包括我们自己。","audio":"风声、稀拉的踢球声","character":"五个少年 — 县中足球队","directorNote":"【第一幕·烂泥】低饱和色调，颓败感","emotionIntensity":35},{"shotNumber":"02","shotType":"中景","visual":"一位拄拐的退役教练走进操场，把一颗崭新的足球扔进泥地","duration":"5s","dialogue":"（教练）想被人看得起，就先把这块烂泥地，跑出名堂来。","audio":"足球落地弹跳、坚定脚步","character":"老教练 — 退役的前职业球员","directorNote":"逆光登场，人物的份量","emotionIntensity":50},{"shotNumber":"03","shotType":"中景","visual":"魔鬼训练，少年们在烈日下折返跑到呕吐，有人想放弃被教练拽起","duration":"6s","dialogue":"（队长）跑不动了……（教练）冠军，都是从跑不动之后开始的。","audio":"喘息、哨声、心跳","character":"教练与队员","directorNote":"【第二幕·淬炼】手持跟拍汗水与挣扎","emotionIntensity":60},{"shotNumber":"04","shotType":"特写","visual":"守门员少年反复扑救，膝盖磨破渗血，却咬牙一次次重新站起","duration":"5s","dialogue":"","audio":"身体砸地声、粗重呼吸","character":"守门员小胖","directorNote":"慢镜特写血与泥，意志的具象","emotionIntensity":70},{"shotNumber":"05","shotType":"中景","visual":"预选赛，曾经嘲笑他们的强队被逼平，看台上第一次有人为他们喝彩","duration":"6s","dialogue":"（解说）爆冷！这支无名小队竟然顶住了！","audio":"哨声、零星到爆发的欢呼","character":"全队","directorNote":"横移展现比分逆转，气势起势","emotionIntensity":75},{"shotNumber":"06","shotType":"近景","visual":"更衣室里，队长读出父亲寄来的信，五个少年红了眼眶又互相捶肩打气","duration":"6s","dialogue":"（队长）我爸说，他这辈子第一次，以我为荣。","audio":"翻信纸声、压抑的哽咽","character":"五个少年","directorNote":"暖光更衣室群像，情绪蓄力","emotionIntensity":65},{"shotNumber":"07","shotType":"远景","visual":"决赛日，体育场座无虚席，五个泥地里走出的少年并肩站上中圈","duration":"6s","dialogue":"","audio":"全场山呼海啸、国歌","character":"全队","directorNote":"【第三幕·决战】大广角仰拍，命运时刻","emotionIntensity":80},{"shotNumber":"08","shotType":"中景","visual":"比分落后，终场前最后一攻，队长带球突破连过三人","duration":"5s","dialogue":"（解说）他还在跑！没有人能拦住他！","audio":"球鞋摩擦、呐喊、急促鼓点","character":"队长","directorNote":"稳定器贴地飞速跟拍，速度燃点","emotionIntensity":90},{"shotNumber":"09","shotType":"特写","visual":"队长起脚怒射，皮球擦着横梁飞入死角，时间在这一刻彻底点燃","duration":"5s","dialogue":"","audio":"球网震动、终场哨、爆炸欢呼","character":"队长","directorNote":"子弹时间环绕射门，全片高潮","emotionIntensity":100},{"shotNumber":"10","shotType":"大远景","visual":"夺冠之夜，少年们把拄拐的教练高高抛起，泥地操场的方向灯火通明","duration":"7s","dialogue":"（旁白）他们说我们是烂泥，可烂泥里，也能开出花来。","audio":"恢宏配乐、欢呼、烟花","character":"全队与教练","directorNote":"航拍拉升庆祝，与开场烂泥地呼应","emotionIntensity":95}]'::jsonb,
  true, NULL
),
(
  '第七夜', '恐怖', '👻', '一名纪录片摄影师独自入住废弃的山中疗养院拍摄，从第一夜起他发现每个夜晚都在重复，而墙上的日历，停在了第七夜。心理恐怖长片。', 'horror', 'long',
  '[{"shotNumber":"01","shotType":"远景","visual":"暮色中山路尽头，一座爬满藤蔓的废弃疗养院隐现在雾里","duration":"6s","dialogue":"","audio":"山风、乌鸦、枯枝断裂","character":"","directorNote":"【第一幕·入住】雾气与长焦压缩，未知压迫","emotionIntensity":35},{"shotNumber":"02","shotType":"中景","visual":"摄影师扛着设备推开锈蚀大门，手电光扫过落满灰尘的接待大厅","duration":"6s","dialogue":"（自语）废弃二十年……正好，没人打扰。","audio":"门轴尖啸、脚步回响","character":"阿哲 — 三十岁，独立纪录片摄影师","directorNote":"手电光是唯一光源，营造管窥恐惧","emotionIntensity":45},{"shotNumber":"03","shotType":"特写","visual":"墙上的旧日历停在第七夜，每一格都被人用红笔重重画了叉","duration":"5s","dialogue":"","audio":"钟摆声、纸张","character":"","directorNote":"微距推近红叉，植入核心谜题","emotionIntensity":55},{"shotNumber":"04","shotType":"中景","visual":"深夜，摄影机自动开始录制，回放里走廊尽头有个本不存在的白衣身影","duration":"6s","dialogue":"（看回放）这……这是什么时候拍的？","audio":"录像电流声、极轻的脚步","character":"阿哲","directorNote":"【第二幕·循环】画中画恐惧，虚实交错","emotionIntensity":70},{"shotNumber":"05","shotType":"近景","visual":"他猛然惊醒，发现日期又回到了第一夜，所有摆设原样复位","duration":"5s","dialogue":"（颤声）昨天……明明已经是第二天了。","audio":"心跳、座钟倒走的诡异声","character":"阿哲","directorNote":"利用相同机位强调循环","emotionIntensity":75},{"shotNumber":"06","shotType":"中景","visual":"阿哲在病房档案里翻到一张老照片，照片里的护士与录像中的白衣人一模一样","duration":"6s","dialogue":"","audio":"翻档案声、风穿过走廊","character":"阿哲","directorNote":"浅景深对焦照片，信息揭示","emotionIntensity":65},{"shotNumber":"07","shotType":"特写","visual":"档案记载：二十年前的第七夜，这里所有人一夜消失，无一生还","duration":"5s","dialogue":"（读档案）第七夜……他们都没能离开。","audio":"纸张翻动、骤起的耳鸣","character":"阿哲","directorNote":"文字特写配音效，恐惧升级","emotionIntensity":80},{"shotNumber":"08","shotType":"中景","visual":"无论怎么逃，走廊总把他绕回原点，墙上的日历一夜夜逼近第七夜","duration":"6s","dialogue":"（嘶吼）放我出去！","audio":"跑动喘息、门一扇扇自动关闭","character":"阿哲","directorNote":"【第三幕·第七夜】走廊无限循环的眩晕调度","emotionIntensity":90},{"shotNumber":"09","shotType":"近景","visual":"第七夜，白衣护士终于转过身，脸上是和阿哲一模一样的容貌","duration":"5s","dialogue":"","audio":"寂静、一声轻柔的女声哼唱","character":"白衣护士","directorNote":"镜面式恐惧的高潮，留白不血腥","emotionIntensity":95},{"shotNumber":"10","shotType":"远景","visual":"数月后，又一名摄影师推开疗养院大门，墙上的日历正停在第七夜","duration":"7s","dialogue":"（旁白）有些地方不会放人离开，它只是在，等下一个客人。","audio":"门轴尖啸、循环般的山风","character":"新的摄影师","directorNote":"与开场同构图，轮回式恐怖收尾","emotionIntensity":70}]'::jsonb,
  true, NULL
),
(
  '车站', '浪漫', '💕', '同一座小城火车站，一对恋人在十年间四次相遇又错过，从青涩到成熟，命运用一班班列车，写下一个关于等待的爱情故事。浪漫长片。', 'romantic', 'long',
  '[{"shotNumber":"01","shotType":"远景","visual":"二〇一五年的小城火车站，绿皮火车进站，蒸汽与人潮交织","duration":"6s","dialogue":"","audio":"火车进站鸣笛、人声鼎沸","character":"","directorNote":"【第一幕·初遇·2015】暖黄胶片质感","emotionIntensity":35},{"shotNumber":"02","shotType":"中景","visual":"慌乱赶车的女孩撞翻男孩的画板，两人蹲在地上手忙脚乱地捡画纸","duration":"5s","dialogue":"（女孩）对不起对不起！（男孩）没事，反正画的就是车站。","audio":"纸张散落、急促道歉、笑","character":"林之、苏念 — 二十岁出头","directorNote":"双人蹲地构图，青涩的初见","emotionIntensity":50},{"shotNumber":"03","shotType":"特写","visual":"男孩把一张画着女孩侧脸的速写塞给她，火车却已鸣笛催促","duration":"4s","dialogue":"（男孩）这张，送你。","audio":"鸣笛、心跳","character":"","directorNote":"浅景深交递速写，心动的定格","emotionIntensity":65},{"shotNumber":"04","shotType":"中景","visual":"二〇一八年，同一站台，两人擦肩而过又同时回头，却被人流冲散","duration":"6s","dialogue":"（旁白）三年后，我们都长大了，也都，有了各自的方向。","audio":"站台广播、嘈杂人流","character":"林之、苏念","directorNote":"【第二幕·错过】慢镜回头与人流冲散的对比","emotionIntensity":60},{"shotNumber":"05","shotType":"近景","visual":"女孩在车窗里看见站台上奔跑寻找的男孩，举手贴上玻璃却没能喊出声","duration":"5s","dialogue":"","audio":"列车启动声、压抑的呼吸","character":"苏念","directorNote":"隔着车窗的手，错过的克制","emotionIntensity":75},{"shotNumber":"06","shotType":"中景","visual":"二〇二一年雨夜车站，两人各自撑伞错身，男孩认出她背包上的旧速写挂件","duration":"6s","dialogue":"（男孩低声）……是你吗？","audio":"雨声、迟疑的脚步","character":"林之、苏念","directorNote":"雨幕与伞，重逢前的迟疑","emotionIntensity":70},{"shotNumber":"07","shotType":"特写","visual":"男孩追上去，发现她无名指上空空如也，松了一口气又紧张得说不出话","duration":"5s","dialogue":"","audio":"雨声渐缓、心跳放大","character":"林之","directorNote":"对焦那只手，信息与情绪并行","emotionIntensity":65},{"shotNumber":"08","shotType":"中景","visual":"两人在站台长椅坐下，聊起这十年走散的人生，肩膀慢慢靠近","duration":"6s","dialogue":"（苏念）这些年，我一直留着那张画。","audio":"夜雨余声、温柔交谈","character":"林之、苏念","directorNote":"【第三幕·重逢·2025】侧后跟拍并肩，暖灯回温","emotionIntensity":80},{"shotNumber":"09","shotType":"近景","visual":"男孩从画夹取出十年来在各地车站画的画，每一张角落都有她的影子","duration":"5s","dialogue":"（林之）其实，我画的每个车站，都在等一个人。","audio":"翻画声、钢琴渐入","character":"林之","directorNote":"一叠画的特写，深情的揭示","emotionIntensity":90},{"shotNumber":"10","shotType":"大远景","visual":"高铁飞驰进站，这一次两人十指相扣登上同一班车，站台的灯渐渐远去","duration":"7s","dialogue":"（旁白）有些人要错过很多班车，才终于，坐上同一趟。","audio":"列车启动、弦乐渐强、鸣笛","character":"林之、苏念","directorNote":"航拍列车驶离，与开场绿皮车呼应收尾","emotionIntensity":85}]'::jsonb,
  true, NULL
);
